apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-fluentd-configmap
  namespace: messaging-app
data:
  fluent-bit.conf: |
    [INPUT]
      Name tail
      Path /var/log/webservice/app.log*
    
    [OUTPUT]
      Name cloudwatch_logs
      Match   *
      region us-east-1
      log_group_name fluent-bit-cloudwatch
      log_stream_prefix from-fluent-bit-
      auto_create_group On