apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-webservice
  namespace: messaging-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
  labels:
    app: webservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      labels:
        app: webservice
    spec:
      serviceAccountName: messaging-service-account
      volumes:
      - name: app-logs
        emptyDir: {}
      - name: fluentd-config
        configMap:
          name: messaging-fluentd-configmap
      containers:
      - name: webservice
        image: ${image}
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /var/log/webservice
            name: app-logs
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: messaging-app-db-secret
                key: DB_PASSWORD

          - name: DB_HOST
            value: messaging-db-service.messaging-app.svc.cluster.local

          - name: DB_USER
            value: testuser

          - name: DB_NAME
            value: db

          - name: DB_PORT
            value: "3306"

        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      - name: fluentd
        image: fluent/fluent-bit
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
          - mountPath: /var/log/webservice
            name: app-logs
          - mountPath: /fluent-bit/etc 
            name: fluentd-config
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
