apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: messaging-webservice-hpa
  namespace: messaging-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: messaging-webservice
  minReplicas: 3  # Minimum number of replicas
  maxReplicas: 10  # Maximum number of replicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60